name: FloatingTexter
main: FloatingTexter\Main
version: 2.0
api: 2.0.0
description: Make floating texts in your server, in your world, at your conditions.
website: https://github.com/Heromine/FloatingTexter
author: Heromine/Jon, Flavius12, AryToNeX